export const getEnvVar = (key: string): string => {
  const envMap: Record<string, string | undefined> = {
    NEXT_PUBLIC_CEDRA_FULLNODE: process.env.NEXT_PUBLIC_CEDRA_FULLNODE,
    NEXT_PUBLIC_CEDRA_INDEXER: process.env.NEXT_PUBLIC_CEDRA_INDEXER,
    NEXT_PUBLIC_CEDRA_FAUCET: process.env.NEXT_PUBLIC_CEDRA_FAUCET,
    NEXT_PUBLIC_CEDRA_EXPLORER: process.env.NEXT_PUBLIC_CEDRA_EXPLORER,
    NEXT_PUBLIC_CEDRA_NFT_MODULE_ADDRESS:
      process.env.NEXT_PUBLIC_CEDRA_NFT_MODULE_ADDRESS,
    NEXT_PUBLIC_CEDRA_NFT_MODULE_NAME:
      process.env.NEXT_PUBLIC_CEDRA_NFT_MODULE_NAME,
    NEXT_PUBLIC_APTOS_FULLNODE: process.env.NEXT_PUBLIC_APTOS_FULLNODE,
    NEXT_PUBLIC_APTOS_FAUCET: process.env.NEXT_PUBLIC_APTOS_FAUCET,
    NEXT_PUBLIC_APTOS_EXPLORER: process.env.NEXT_PUBLIC_APTOS_EXPLORER,
    NEXT_PUBLIC_APTOS_NFT_MODULE_ADDRESS:
      process.env.NEXT_PUBLIC_APTOS_NFT_MODULE_ADDRESS,
    NEXT_PUBLIC_APTOS_NFT_MODULE_NAME:
      process.env.NEXT_PUBLIC_APTOS_NFT_MODULE_NAME,
    NEXT_PUBLIC_SEPOLIA_CONTRACT_ADDRESS:
      process.env.NEXT_PUBLIC_SEPOLIA_CONTRACT_ADDRESS,
    NEXT_PUBLIC_BSC_TESTNET_CONTRACT_ADDRESS:
      process.env.NEXT_PUBLIC_BSC_TESTNET_CONTRACT_ADDRESS,
    NEXT_PUBLIC_ARBITRUM_SEPOLIA_CONTRACT_ADDRESS:
      process.env.NEXT_PUBLIC_ARBITRUM_SEPOLIA_CONTRACT_ADDRESS,
    NEXT_PUBLIC_IPFS_GATEWAY_1: process.env.NEXT_PUBLIC_IPFS_GATEWAY_1,
    NEXT_PUBLIC_IPFS_GATEWAY_2: process.env.NEXT_PUBLIC_IPFS_GATEWAY_2,
    NEXT_PUBLIC_IPFS_GATEWAY_3: process.env.NEXT_PUBLIC_IPFS_GATEWAY_3,
    NEXT_PUBLIC_PETRA_WALLET_URL: process.env.NEXT_PUBLIC_PETRA_WALLET_URL,
    NEXT_PUBLIC_PONTEM_WALLET_URL: process.env.NEXT_PUBLIC_PONTEM_WALLET_URL,
    NEXT_PUBLIC_NIGHTLY_WALLET_URL: process.env.NEXT_PUBLIC_NIGHTLY_WALLET_URL,
    NEXT_PUBLIC_ZEDRA_WALLET_URL: process.env.NEXT_PUBLIC_ZEDRA_WALLET_URL,
    NEXT_PUBLIC_METAMASK_WALLET_URL:
      process.env.NEXT_PUBLIC_METAMASK_WALLET_URL,
  };

  const value = envMap[key];
  if (!value) {
    throw new Error(`Missing environment variable: ${key}`);
  }
  return value;
};
